In [15]:
import numpy as np
from numpy import linalg as LA  # Notar que importamos linalg con nickname LA

In [16]:
c1 = 2*(np.random.rand(3,1)-0.5)
print(c1)
c1.shape

[[-0.37663548]
 [-0.76693051]
 [ 0.51628219]]


(3, 1)

In [17]:
"""Queremos entender el proceso de Gram-Schmidt."""

# Vamos a generar tres vectores al azar
# las chances son que van a ser linealmente independientes (Por que?)

c1 = 2*(np.random.rand(3,1)-0.5) # c1, c2 y c3 son dos vectores 3x1 con elementos aleatorios en el 
c2 = 2*(np.random.rand(3,1)-0.5) # rango (-1,1). Pregunta: por que puedo sumar un vector                             
c3 = 2*(np.random.rand(3,1)-0.5) # y un escalar? Buscar "numpy broadcasting"

print("c1 =", c1)
print("c2 =", c2)
print("c3 =", c3)

c1 = [[-0.25546086]
 [ 0.33425747]
 [ 0.56072088]]
c2 = [[-0.49927933]
 [-0.91415459]
 [-0.6241968 ]]
c3 = [[ 0.7498975 ]
 [-0.70980937]
 [-0.98959244]]


In [18]:
# si queremos chequear que no son linealmente independientes

print(np.dot(np.transpose(c1),c2)/(LA.norm(c1)*LA.norm(c2)))
# EL producto escalar entre c1 y c2 es c1.c2 = |c1||c2|cos(theta), entonces, 
# c1.c2/(|c1||c2|) = cos(theta), por lo que si este numero NO es 1 ni -1, sabemos que los
# vectores c1 y c2 no son linealmente independientes.
# Lo mismo vale para c3
# Pero ojo, c3 pudiera no ser proporcional ni a c1 ni a c2 y aun asi ser linealmente dependiente
# de ambos

[[-0.62029417]]


In [19]:
n1 = c1/LA.norm(c1)          # dividiendo al vector por su magnitud obtenemos un vector
                                # en la misma direccion pero de magnitud (o "norma") 1.
print(n1)
print(np.dot(np.transpose(n1),n1))  # chequeamos que su norma es 1 multiplicandolo
                                      # escalarmente por si mismo


[[-0.36442525]
 [ 0.47683181]
 [ 0.79989103]]
[[1.]]


In [20]:
# Ya tenemos el vector n1, que es proporcional a c1, pero de magnitud 1.
# Ahora queremos construir el vector n2.
# Recordedmos que n2 es tiene que ser ortonormal con n1, y tal que el span de {n1, n2}
# sea el mismo que el de {c1, c2}
# El mecanismo es: 
# 1) calculamos la componente de c2 paralela a n1, la llamamos P_c2_n1
P_c2_n1 = np.dot(np.transpose(n1),c2)*n1 # la proyeccion del vector c2 sobre el vector n1 es
                                              # (c2.n1) n1 
                                              # c2.n1 es producto escalar de c2 por n1,
                                              # que da la magnitud de la proyeccion de c2 
                                              # sobre sobre n1. Luego, al multiplicarlo por n1,
                                              # el vector resultante apunta en la direccion de n1
                                              # La formula general inluye una division por 
                                              # (n1.n1)
                                              # en este caso no es necesario porque (n1.n1) = 1
print(P_c2_n1)

[[ 0.27449874]
 [-0.35916756]
 [-0.60250785]]


In [21]:
# 2) Calculamos la componente de c2 perpendicular a n1.
#    A dicha componente la llamamos P_c2_perp_n1 (largo pero explicito... :))
# 2_a) Se calcula simplemente restandole a c2 la componente paralela a n1 que 
#      ya calculamos en el paso 1.
#      Naturalmente, P_c2_perp_n1 tiene que ser perpendicular a n1. 
P_c2_perp_n1 = c2 - P_c2_n1  # la proyeccion del vector c2 perpendicular al vector n1 es
                                  # c2 - P_c2_n1
print(P_c2_perp_n1)
print(np.dot(np.transpose(P_c2_perp_n1),P_c2_n1)) # para chequear la perpendicularidad de
                                                      # P_c2_perp_n1 y P_c2_n1
                                                      # calculamos su producto escalar

[[-0.77377807]
 [-0.55498703]
 [-0.02168895]]
[[2.60208521e-17]]


In [22]:
print(c2)                          # Chequamos que c2 = P_c2_n1 + P_c2_perp_n1 de dos maneras
print(P_c2_n1 + P_c2_perp_n1)   # 1- Observando numericamente si coinciden
c2 == P_c2_n1 + P_c2_perp_n1   # 2- Preguntandole a Python con "=="
                                    # (ojo con este ultimo metodo porque puede llegar a dar
                                    # False por errores que las maquinas siempre cometen)

[[-0.49927933]
 [-0.91415459]
 [-0.6241968 ]]
[[-0.49927933]
 [-0.91415459]
 [-0.6241968 ]]


array([[ True],
       [ True],
       [ True]])

In [23]:
# 3) Calculamos n2 (que tiene que tener norma 1) simplemente dividiendo a 
#    P_c2_perp_n1 por su norma.
# 3_a) Chequeamos que el conjunto {n1, n2} es ortonormal
#
n2 = P_c2_perp_n1/LA.norm(P_c2_perp_n1) # Generamos n2, que es el vector de norma = 1
print(n2)                                          # perpendicular a n1 
print(np.dot(np.transpose(n2),n2))                # El conjunto {n1, n2} es ortonormal y
print(np.dot(np.transpose(n1),n2))                # genera el subespacio de R3 en el que "viven"
                                                   # c1 y c2

[[-0.81238456]
 [-0.58267727]
 [-0.02277109]]
[[1.]]
[[1.73472348e-17]]


In [24]:
# 4) Queremos calcular la componente de c3 perpendicular a n1 y n2 (y por lo tanto,
#    tambien perpendicular a c1 y c2)
# 4_a) Primero calculamos las componentes de c3 paraleleas a n1 y n2.

P_c3_n1 = np.dot(np.transpose(n1),c3)*n1 # Continuamos con el proceso de Gram-Schmidt con
P_c3_n2 = np.dot(np.transpose(n2),c3)*n2 # el vector c3. Ahora estamos calculando las
print(P_c3_n1)                              # proyecciones de c3 sobre n1 y n2
print(P_c3_n2)                          

[[ 0.51140065]
 [-0.6691416 ]
 [-1.12249299]]
[[0.14060855]
 [0.10085052]
 [0.00394125]]


In [25]:
# 4_b) Calculamos la componente de c3 perpendicular a n1 y n2.
#      A esto lo hacemos simplemente restando de c3 las componentes paralelas a n1 y a n2

P_c3_perp_n1yn2 = c3 - P_c3_n1 - P_c3_n2 # Extraemos la componente de c3 perpendicular al plano
                                         # spanned por n1 y n2
print(P_c3_perp_n1yn2)                     

[[ 0.0978883 ]
 [-0.14151829]
 [ 0.1289593 ]]


In [26]:
# Por como lo construimos, P_c3_perp_n1yn2 tiene que ser ortogonal a n1 y n2
# Comprobemos eso:
print(np.dot(np.transpose(n2),P_c3_perp_n1yn2))               
print(np.dot(np.transpose(n1),P_c3_perp_n1yn2))

[[5.72458747e-17]]
[[-1.38777878e-17]]


In [27]:
# Calculemos entonces el vector proporcional a P_c3_perp_n1yn2 pero normalizado a 1:
n3 = P_c3_perp_n1yn2/LA.norm(P_c3_perp_n1yn2)
print(n3)
# Constatemos que esta normalizado a 1
print(np.dot(np.transpose(n3),n3))
# Esto finaliza nuestro proceso de construccion de una base ortonormal de R3:
# {n1, n2, n3}

[[ 0.45522034]
 [-0.65811748]
 [ 0.59971311]]
[[1.]]


In [28]:
# Resolver HW 5.14 y 5.15, p. 32, de https://ucema.edu.ar/publicaciones/download/documentos/689.pdf