In [1]:
import numpy as np
from numpy import linalg as LA  # Notar que importamos linalg con nickname LA

In [2]:
c1 = 2*(np.random.rand(3,1)-0.5) # c1 y c2 son dos vectores 3x1 con elementos aleatorios en el 
c2 = 2*(np.random.rand(3,1)-0.5) # rango (-1,1). Pregunta: por que puedo sumar un vector
                                 # y un escalar?Buscar "numpy broadcasting"
print(np.dot(np.transpose(c1),c2)/(LA.norm(c1)*LA.norm(c2)))
# EL producto escalar entre c1 y c2 es c1.c2 = |c1||c2|cos(theta), entonces, 
# c1.c2/(|c1||c2|) = cos(theta), por lo que si este numero NO es 1 ni -1, sabemos que los
# vectores c1 y c2 no son linealmente independientes.
# Por otra parte, habiendo generado c1 y c2 al azar, las chances de que sean linealmente
# dependientes son minusculas. Igualmente vale la pena probar que no es 1.

[[0.18816379]]


In [3]:
d1 = 2*(np.random.rand()-0.5) # d1 y d2 son escalares en el rango (-1,1)
d2 = 2*(np.random.rand()-0.5)
c3 = d1*c1 + d2*c2  # c3, por construccion, es linealmente dependiente de c1 y c2.
print(c1)
print(c2)
print(c3) # Sin embargo eso NO es obvio a simple vista

[[ 0.5605616 ]
 [-0.474587  ]
 [ 0.85215268]]
[[-0.37543578]
 [-0.46214947]
 [ 0.14162217]]
[[0.56299506]
 [0.20387462]
 [0.23435456]]


In [4]:
A = np.concatenate((c1, c2, c3), axis=1) # construimos la matriz A con columnas c1, c2 y c3
print(A.shape)
print(A)  # chequear que, efectivamente, las columnas de A son c1, c2 y c3
LA.matrix_rank(A)  # EL rango de la matriz es el numero de columnas linealmente independientes

(3, 3)
[[ 0.5605616  -0.37543578  0.56299506]
 [-0.474587   -0.46214947  0.20387462]
 [ 0.85215268  0.14162217  0.23435456]]


2

In [5]:
# Construimos explicitamente A de modo que una de sus 3 columnas es linealmente dependiente
# de las otras dos. Ahora hagamos de cuenta que no sabemos esto. Por cierto que, dado
# que generamos las componentes de manera aleatoria, la dependencia linal no es obvia
# a simple vista, pero por construccion sabemos que esta ahi.
#
# Entonces, recordemos:
# 1) c1 y c2 son linealmente independiente. 
# 2) c3 es linealmente Dependiente de {c1, c2}
# 3) Como los coeficientes fueron generados al azar, con probabilidad 0.99999999999.....
#    c3 es lineamente independiente de c1 y c3 como vectores individuales,
#    PERO ESTA EN EL PLANO GENERADO POR c1 y c2.
# 4) Por lo tanto, con altisima probabilidad, los pares {c1, c3} y {c2, c3} tambien
#    son linealmente idependientes (chequearlo).
# 5) Sin embargo, la terna {c1, c2, c3} es linealmente dependiente. (comprobarlo en Geogebra)
# 6) Esto implica que el SPAN de {c1, c2, c3} es un plano, no es R3.
#
# De ahora en mas, como dije mas arriba, hacemos de cuenta que
#
#            NO SABEMOS QUE LAS COLUMNAS DE A SON LINEALMENTE DEPENDIENTES!

In [6]:
np.linalg.det(A)  # Una manera automatica de chequear si las columnas son linealmente
                  # dependientes es calcular el determinante. Si da cero son linealmente
                  # dependients. Ver el video de determinantes de 3Blue1Brown y entender  
                  # el significado geometrico del determinante (como se
                  # transforman los volumenes) para entender por que si son lin dep el det
                  # tiene que ser cero.
            
                  # Pero, aunque el determinante de A sea cero, y por lo tanto no podamos
                  # calcular la inversa de A, el sistema A x = b puede
                  # tener solucion si justo b pertence al subespacio spanned por las columnas
                  # de A. Vamos a averiguarlo con el metodo de Gram-Schmidt

1.894779600340745e-17

In [7]:
# Como estamos jugando a que no sabemos como se construyo A, extraigamos los vectores columnas y,
# a travez del proceso de Gram-Schmidt, obtengamos con una base ortonormal
# del subespacio generado por el span de las columnas de A
c1A = A[:, [0]]  # columna 1 de la matriz A 
print(c1A.shape)
print(c1A)
c2A = A[:, [1]]  # columna 2 de la matriz A 
print(c2A.shape)
print(c2A)
c3A = A[:, [2]]  # columna 3 de la matriz A
print(c3A.shape)
print(c3A)

(3, 1)
[[ 0.5605616 ]
 [-0.474587  ]
 [ 0.85215268]]
(3, 1)
[[-0.37543578]
 [-0.46214947]
 [ 0.14162217]]
(3, 1)
[[0.56299506]
 [0.20387462]
 [0.23435456]]


In [8]:
n1A = c1A/LA.norm(c1A)          # dividiendo al vector por su magnitud obtenemos un vector
                                # en la misma direccion pero de magnitud (o "norma") 1.
print(n1A)
print(np.dot(np.transpose(n1A),n1A))  # chequeamos que su norma es 1 multiplicandolo
                                      # escalarmente por si mismo

[[ 0.49827672]
 [-0.42185489]
 [ 0.75746865]]
[[1.]]


In [9]:
# Ya tenemos el vector n1A, que es proporcional a c1A, pero de magnitud 1.
# Ahora queremos construir el vector n2A.
# Recordedmos que n2A es tiene que ser ortonormal con n1A, y tal que el span de {n1A, n2A}
# sea el mismo que el de {c1A, c2A}
# El mecanismo es: 
# 1) calculamos la componente de c2A paralela a n1A, la llamamos P_c2A_n1A
P_c2A_n1A = np.dot(np.transpose(n1A),c2A)*n1A # la proyeccion del vector c2A sobre el vector n1A es
                                              # (c2A.n1A) n1A 
                                              # c2A.n1A es producto escalar de C2A por n1A,
                                              # que da la magnitud de la proyeccion de c2A 
                                              # sobre sobre n1A. Luego, al multiplicarlo por n1A,
                                              # el vector resultante apunta en la direccion de n1A
                                              # La formula general inluye una division por 
                                              # (n1A.n1A)
                                              # en este caso no es necesario porque (n1A.n1A) = 1
print(P_c2A_n1A)

[[ 0.05738327]
 [-0.04858227]
 [ 0.08723271]]


In [10]:
# 2) Calculamos la componente de c2A perpendicular a n1A.
#    A dicha componente la llamamos P_c2A_perp_n1A (largo pero explicito... :))
# 2_a) Se calcula simplemente restandole a c2A la componente paralela a n1A que 
#      ya calculamos en el paso 1.
#      Naturalmente, P_c2A_perp_n1A tiene que ser perpendicular a n1A. 
P_c2A_perp_n1A = c2A - P_c2A_n1A  # la proyeccion del vector c2A perpendicular al vector n1A es
                                  # c2A - P_c2A_n1A
print(P_c2A_perp_n1A)
print(np.dot(np.transpose(P_c2A_perp_n1A),P_c2A_n1A)) # para chequear la perpendicularidad de
                                                      # P_c2A_perp_n1A y P_c2A_n1A
                                                      # calculamos su producto escalar

[[-0.43281905]
 [-0.4135672 ]
 [ 0.05438946]]
[[-4.33680869e-18]]


In [11]:
print(c2A)                          # Chequamos que c2A = P_c2A_n1A + P_c2A_perp_n1A de dos maneras
print(P_c2A_n1A + P_c2A_perp_n1A)   # 1- Observando numericamente si coinciden
c2A == P_c2A_n1A + P_c2A_perp_n1A   # 2- Preguntandole a Python con "=="
                                    # (ojo con este ultimo metodo porque puede llegar a dar
                                    # False por errores que las maquinas siempre cometen)

[[-0.37543578]
 [-0.46214947]
 [ 0.14162217]]
[[-0.37543578]
 [-0.46214947]
 [ 0.14162217]]


array([[ True],
       [ True],
       [ True]])

In [12]:
# 3) Calculamos n2A (que tiene que tener norma 1) simplemente dividiendo a 
#    P_c2A_perp_n1A por su norma.
# 3_a) Chequeamos que el conjunto {n1A, n2A} es ortonormal
#
n2A = P_c2A_perp_n1A/LA.norm(P_c2A_perp_n1A) # Generamos n2A, que es el vector de norma = 1
print(n2A)                                          # perpendicular a n1A 
print(np.dot(np.transpose(n2A),n2A))                # El conjunto {n1A, n2A} es ortonormal y
print(np.dot(np.transpose(n1A),n2A))                # genera el subespacio de R3 en el que "viven"
                                                    # c1A y c2A

[[-0.72003787]
 [-0.68801048]
 [ 0.09048232]]
[[1.]]
[[1.38777878e-17]]


In [13]:
# 4) Queremos calcular la componente de c3A perpendicular a n1A y n2A (y por lo tanto,
#    tambien perpendicular a c1A y c2A)
# 4_a) Primero calculamos las componentes de c3A paraleleas a n1A y n2A.

P_c3A_n1A = np.dot(np.transpose(n1A),c3A)*n1A # Continuamos con el proceso de Gram-Schmidt con
P_c3A_n2A = np.dot(np.transpose(n2A),c3A)*n2A # el vector c3A. Ahora estamos calculando las
print(P_c3A_n1A)                              # proyecciones de c3A sobre n1A y n2A
print(P_c3A_n2A)                              

[[ 0.1853779 ]
 [-0.15694607]
 [ 0.28180717]]
[[ 0.37761716]
 [ 0.36082069]
 [-0.04745261]]


In [14]:
# 4_b) Calculamos la componente de c3A perpendicular a n1A y n2A.
#      A esto lo hacemos simplemente restando de c3A las componentes paralelas a n1A y a n2A

P_c3A_perp_n1Ayn2A = c3A - P_c3A_n1A - P_c3A_n2A # Intentamos extraer la componente de c3A que
print(P_c3A_perp_n1Ayn2A)                        # NO esta en el subespacio spanned por 
                                                 # {n1A, n2A} pero nos da zero!
                                                 # Esto significa que c3A el linealmente
                                                 # dependiente de c1A y c2A 
                                                 #
                                                 # Por eso concluimos que el sistema
                                                 # A x = b
                                                 # solo tendra solucion si justo b pertenece
                                                 # al mismo subespacio.

[[-1.11022302e-16]
 [-1.66533454e-16]
 [ 1.04083409e-16]]


In [15]:
# Nuestro proposito es entender cuando la ecuacion A x = b va a tener solucion.
# Y que tipo de soluciones tiene
#
# Miremos el lado derecho de la ecuacion: A x
# Recordemos que A x, donde x es un vector 3x1 de coeficientes incognita,
# tiene el significado geometrico de una combinacion lineal de los vecores columna de A.
# Los coeficientes de esa combinacion son los componentes incognita de x.
# 
# Ahora miremos el lado izquierdo: b
# la unica manera de que la ecuacion A x = b tenga solucion es que b viva en el subespacio spanned
# por las columnas de A: C(A).
# Entonces, si generamos un b al azar, con probabilidad ~1 la ecuacion no va atener solucion:
b = 2*(np.random.rand(3,1)-0.5)
x = LA.solve(A, b)  
print(x)
# numericamente esto aparece como un vector gigante

[[ 6.70049560e+15]
 [-1.39184470e+16]
 [-1.59531125e+16]]


In [16]:
# Chequeamos que, efectivamente, x NO es una solucion de la ecuacion A x = b, o de A x - b = 0
print(np.dot(A,x)-b)

[[-0.24292012]
 [ 0.15437994]
 [-0.10050847]]


In [17]:
# Supongamos entonces que b vive en el subespacio
# generado por las columnas de A. Como generamos un b asi?
# Asi:

bb1 = 2*(np.random.rand()-0.5) # bb1 y bb2 son escalares en el rango (-1,1)
bb2 = 2*(np.random.rand()-0.5)
b = bb1*n1A + bb2*n2A            # Por que puedo estar seguro de que esto vive en el subespacio
print(b)                       # generado por las columnas de A? Numericamente no resulta obvio.

[[ 0.50367618]
 [ 0.78123655]
 [-0.33724046]]


In [18]:
x = LA.solve(A, b)                   # Asi resolvemos la ecuacion "singular", pero
                                     # todavia no entendemos conceptualmente como
                                     # encontrar esta solucion
print(x)

[[-0.75883776]
 [-0.25956635]
 [ 1.47710176]]


In [19]:
# Chequeamos que, efectivamente, x es una solucion de la ecuacion A x = b, o de A x - b = 0
print(np.dot(A,x)-b)

[[0.00000000e+00]
 [0.00000000e+00]
 [5.55111512e-17]]


In [20]:
# Como vimos, si hubiera 2 soluciones distintas entre si, x1 y x2 , de la ecuacion
# A x = b, esto es, si A x1 = b y A x2 = b y x1 distinto de x2,
# Entonces A (x1 - x2) = 0, donde (x1 - x2) es distinto del vector 0.
# En otras palabras, existirian vectores "d" distintos de cero tales que
#                       A d = 0
# Si d es solucion de la ecuacion "homogenea", lambda*d, donde lambda es cualquier
# numero real, tambien lo es.
# Que significado geometrico tiene d?
# Las componentes de d son incognita, llamemoslas d1, d2 y d3.
#                        A d = d1*c1A + d2*c2A + d3* c3A = 0
# es decir, A d es una combinacion lineal de los vectores columna de A que da como resultado
# el vector 0.
# Pero que exista tal combinacion lineal (no todos cero) implica que, por ejemplo
# (si d3 es distinto de cero):
#                    c3A = -(d1/d3)*c1A - (d2/d3)*c2A 
# es decir, que la tercera columna sea combinacion linal de las primeras dos.
# Es decir, implica que los vectores columna no son linealmente independientes. 
# 
# Esto implica que 
#                 (d1/d3)*c1A + (d2/d3)*c2A + c3A = 0

In [21]:
# recuerden que en una de las primeras celdas, construimos la columna c3 de A asi:
# d1 = 2*(np.random.rand()-0.5) 
# d2 = 2*(np.random.rand()-0.5)
# c3 = d1*c1 + d2*c2  # c3, por construccion, es linealmente dependiente de c1 y c2.
# Esto significa que el vector
x_0 = np.array([[-d1],[-d2],[1]])
print(x_0)
# tiene que ser solucion de la ecuacion homogenea A x = 0. Probemos:
np.dot(A,x_0)

[[-0.42001181]
 [ 0.87245965]
 [ 1.        ]]


array([[0.],
       [0.],
       [0.]])

In [22]:
# Entonces x_0 multiplicado por cualquier escalar tambien tiene que ser solucion:
lambd = 20*(np.random.rand()-0.5) # numero aleatorio entre -10 y 10
x_01 = lambd*x_0 # ojo que la palabra lambda esta protegida
np.dot(A,x_01)

array([[0.0000000e+00],
       [4.4408921e-16],
       [0.0000000e+00]])

In [23]:
# Por lo tanto la solucion general de A x = b es una solucion particular x mas 
# una solucion cualquiera de la ecuacion A x = 0 (que llamamos x_01 = lambd*x_0):
print(np.dot(A,x + x_01) - b)

[[1.11022302e-15]
 [4.44089210e-16]
 [5.55111512e-17]]


In [24]:
# Notar que en este caso la matriz A fue construida a proposito de modo que
# conocemos como construir la solucion de A x = 0.
# En casos realistas esto no es asi. La semana que viene aprenderemos a resolverla
# en general.

In [25]:
'''Autovalores y Autovectores'''

'Autovalores y Autovectores'

In [26]:
n=2
A = np.random.randn(n,n)
print(A)

[[-0.02102339 -0.30929255]
 [-0.56281921 -1.21968238]]


In [27]:
w, v = LA.eig(A) # ver https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.eig.html
print(w.shape)
print(v.shape)
print(w) # w es (2,) ((n,) en general), y cada componente es un autovalor de A LEER que significa (2,)
print(v) # v es (2,2) ((n,n) en general), y cada columna es un autovector de A

(2,)
(2, 2)
[ 0.10990162 -1.35060738]
[[ 0.92089195  0.22657394]
 [-0.38981793  0.97399397]]


In [28]:
AutoV1_A = v[:, [0]]
AutoV2_A = v[:, [1]]
print(AutoV1_A)
print(LA.norm(AutoV1_A))
print(AutoV2_A)
print(LA.norm(AutoV2_A))
print(np.dot(A,AutoV1_A)/AutoV1_A) # comprobamos que AutoV1_A es un autovector de A
                                   # con autovalor w[0]. (division por vector es comp. a comp.)
print(np.dot(A,AutoV2_A)/AutoV2_A) 

[[ 0.92089195]
 [-0.38981793]]
1.0
[[0.22657394]
 [0.97399397]]
0.9999999999999999
[[0.10990162]
 [0.10990162]]
[[-1.35060738]
 [-1.35060738]]


In [29]:
# Comprovar visualmente en Geogebra que no son en general ortogonales
print(np.dot(np.transpose(AutoV1_A),AutoV2_A))

[[-0.1710302]]


In [30]:
# A = (A + A^T)/2 + (A - A^T)/2, (A + A^T)/2 es simetrica, (A - A^T)/2 antisimetrica
As = (A + np.transpose(A))/2
print(As)

[[-0.02102339 -0.43605588]
 [-0.43605588 -1.21968238]]


In [31]:
ws, vs = LA.eig(As) 
print(ws) 
print(vs)

[ 0.12082225 -1.36152801]
[[ 0.95095232  0.3093375 ]
 [-0.3093375   0.95095232]]


In [32]:
AutoV1_As = vs[:, [0]]
AutoV2_As = vs[:, [1]]
print(AutoV1_As)
print(AutoV2_As)
print(np.dot(np.transpose(AutoV1_As),AutoV2_As)) # Los autovectores de una matriz simetrica
                                                 # son ortogonales entre si

[[ 0.95095232]
 [-0.3093375 ]]
[[0.3093375 ]
 [0.95095232]]
[[0.]]
